In [28]:
import sportswrangler as sw
from sleeper.api import (
    get_rosters,
    get_users_in_league,
    get_all_players,
)
import pandas as pd

In [29]:
LEAGUE_ID = "1180568858700410880"
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)

In [30]:
nfl_players = get_all_players(sport="nfl")

In [31]:
rosters = get_rosters(league_id=LEAGUE_ID)
# rosters

In [32]:
rosters_df = pd.DataFrame(rosters)
# rosters_df

In [33]:
league_users = get_users_in_league(league_id=LEAGUE_ID)
# league_users

In [34]:
users_df = pd.DataFrame(league_users)
users_df = users_df[["user_id", "display_name"]]
# users_df

In [35]:
players_owner = rosters_df[["players", "owner_id"]]
# players_owner

In [36]:
joined_df = players_owner.join(users_df.set_index("user_id"), on="owner_id")
# joined_df

Keepers

- BrunsonBurner3
    
    Sleeper league chat - 05/05/2025
    - Stroud
    - Ward

- jarede2205

    Sleeper dm - 05/05/2025
    - Mahomes

- jaywieland

    iMessage - 05/08/2025
    - JJ

- ChimpertonxHxMcgee

    Sleeper dm - 05/13/2025 7:50 PM ET
    - Maye


- ColeB1998

    Sleeper dm - 05/06/2025
    - Lawrence
    - Penix

- msmith21

    Sleeper league chat - 05/05/2025
    - Love
    - Dart


- TKSuperMan21

    iMessage - 05/05/2025
    - Hurts
    - Murray

- BearsRDaTruth

    - CW
    - Herbo

- 2chambzz

    iMessage - 05/10/2025
    - Burrow
    - Nix

- makoerner

    Sleeper league chat - 05/05/2025
    Sleeper dm - 05/07/2025
    - Lamar
    - Purdy

- BigDoba

    iMessage - 05/07/2025
    - Daniels
    - Young

- JreezyC

    iMessage - 05/06/2025
    - Allen
    - Baker

In [38]:
designated_keepers = [
# BrunsonBurner3
    "C.J. Stroud",
    "Cam Ward",
# jarede2205
    "Patrick Mahomes",
# jaywieland
    "J.J. McCarthy",
# ChimpertonxHxMcgee
    "Drake Maye",
# ColeB1998
    "Trevor Lawrence",
    "Michael Penix Jr.",
# msmith21
    "Jordan Love",
    "Jaxson Dart",
# TKSuperMan21
    "Jalen Hurts",
    "Kyler Murray",
# BearsRDaTruth
    "Justin Herbert",
    "Caleb Williams",
# 2chambzz
    "Joe Burrow",
    "Bo Nix",
# makoerner
    "Lamar Jackson",
    "Brock Purdy",
# BigDoba
    "Jayden Daniels",
    "Bryce Young",
# JreezyC
    "Josh Allen",
    "Baker Mayfield",
]

In [39]:
# Flatten the players lists into rows with owner info
flattened_players = joined_df.explode('players')

# Convert player IDs to player details
def get_player_details(player_id):
    player = nfl_players.get(str(player_id))
    if player and player.get('position') == 'QB':
        return {
            'playerName': player.get('full_name'),
            'position': player.get('position'), 
            'team': player.get('team')
        }
    return None

flattened_players['player_details'] = flattened_players['players'].apply(get_player_details)
flattened_players = flattened_players[flattened_players['player_details'].notna()]
# Flatten the player_details dictionary into separate columns
flattened_players = pd.DataFrame([
    {**{'players': row['players'], 'owner_id': row['owner_id'], 'display_name': row['display_name']}, 
     **row['player_details']} 
    for _, row in flattened_players.iterrows()
])
flattened_players = flattened_players.drop(['players'], axis=1)
# Fix Michael Penix's name
flattened_players.loc[flattened_players['playerName'] == 'Michael Penix', 'playerName'] = 'Michael Penix Jr.'
# Fix Cam Ward's name
flattened_players.loc[flattened_players['playerName'] == 'Cameron Ward', 'playerName'] = 'Cam Ward'

flattened_players = flattened_players[flattened_players['playerName'].isin(designated_keepers)]

flattened_players

              owner_id        display_name         playerName position team
0   733146304376606720       BearsRDaTruth     Caleb Williams       QB  CHI
1   733146304376606720       BearsRDaTruth     Justin Herbert       QB  LAC
3   868657255933997056          jaywieland      J.J. McCarthy       QB  MIN
5   880677433999859712        TKSuperMan21       Kyler Murray       QB  ARI
6   880677433999859712        TKSuperMan21        Jalen Hurts       QB  PHI
7   606584542500835328  ChimpertonxHxMcgee         Drake Maye       QB   NE
10  862814489060442112            2chambzz             Bo Nix       QB  DEN
12  862814489060442112            2chambzz         Joe Burrow       QB  CIN
13  467062850880270336           makoerner      Lamar Jackson       QB  BAL
14  467062850880270336           makoerner        Brock Purdy       QB   SF
15  871472531377451008            msmith21        Jaxson Dart       QB  NYG
18  871472531377451008            msmith21        Jordan Love       QB   GB
20  728992249169436672             JreezyC     Baker Mayfield       QB   TB
21  728992249169436672             JreezyC         Josh Allen       QB  BUF
22  995406796682551296          jarede2205    Patrick Mahomes       QB   KC
23  676939846786314240           ColeB1998  Michael Penix Jr.       QB  ATL
25  676939846786314240           ColeB1998    Trevor Lawrence       QB  JAX
27  883575245750292480      BrunsonBurner3           Cam Ward       QB  TEN
29  883575245750292480      BrunsonBurner3        C.J. Stroud       QB  HOU
30  871485725609267200             BigDoba     Jayden Daniels       QB  WAS
32  871485725609267200             BigDoba        Bryce Young       QB  CAR

In [40]:
ktc_wr = sw.KeepTradeCutWrangler(preferred_dataframe='pandas')
rankings = ktc_wr.get_player_rankings()
# rankings

/var/folders/vx/ykltqjpn1dl8cbk5z64tn0gm0000gn/T/ipykernel_94266/3545606853.py:1: UserWarning: A custom validator is returning a value other than `self`.
Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.
See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.
  ktc_wr = sw.KeepTradeCutWrangler(preferred_dataframe='pandas')

In [41]:
qb_rankings = rankings[rankings['position'] == 'QB']
qb_rankings = qb_rankings[['playerName', 'superflexValues_value']]
qb_rankings = qb_rankings.sort_values(by='superflexValues_value', ascending=False)
# qb_rankings

In [42]:
# Merge flattened_players with qb_rankings on name, position and team
merged_df = flattened_players.merge(
    qb_rankings,
    how='left',
    on=['playerName']
)

# Sort by superflexValues_value descending
merged_df = merged_df.sort_values('superflexValues_value', ascending=False)

merged_df

,owner_id,display_name,playerName,position,team,superflexValues_value
13,728992249169436672,JreezyC,Josh Allen,QB,BUF,9993
19,871485725609267200,BigDoba,Jayden Daniels,QB,WAS,9991
8,467062850880270336,makoerner,Lamar Jackson,QB,BAL,9468
7,862814489060442112,2chambzz,Joe Burrow,QB,CIN,8288
4,880677433999859712,TKSuperMan21,Jalen Hurts,QB,PHI,7985
14,995406796682551296,jarede2205,Patrick Mahomes,QB,KC,7133
5,606584542500835328,ChimpertonxHxMcgee,Drake Maye,QB,NE,6775
18,883575245750292480,BrunsonBurner3,C.J. Stroud,QB,HOU,6769
0,733146304376606720,BearsRDaTruth,Caleb Williams,QB,CHI,6750
1,733146304376606720,BearsRDaTruth,Justin Herbert,QB,LAC,6709
6,862814489060442112,2chambzz,Bo Nix,QB,DEN,6448
11,871472531377451008,msmith21,Jordan Love,QB,GB,6281
3,880677433999859712,TKSuperMan21,Kyler Murray,QB,ARI,5574
17,883575245750292480,BrunsonBurner3,Cam Ward,QB,TEN,5547
9,467062850880270336,makoerner,Brock Purdy,QB,SF,5493
12,728992249169436672,JreezyC,Baker Mayfield,QB,TB,5471
16,676939846786314240,ColeB1998,Trevor Lawrence,QB,JAX,5450
2,868657255933997056,jaywieland,J.J. McCarthy,QB,MIN,5449
15,676939846786314240,ColeB1998,Michael Penix Jr.,QB,ATL,5360
20,871485725609267200,BigDoba,Bryce Young,QB,CAR,5040
10,871472531377451008,msmith21,Jaxson Dart,QB,NYG,4403

In [43]:
# Group by owner_id and calculate average and total values
qb_values = merged_df.groupby('owner_id').agg({
    'superflexValues_value': ['mean', 'sum']
}).reset_index()

# Rename columns
qb_values.columns = ['owner_id', 'avg_value', 'total_value']

# Merge with display names
qb_values = qb_values.merge(
    merged_df[['owner_id', 'display_name']].drop_duplicates(),
    on='owner_id'
)

# qb_values
# Sort by total value
qb_values.sort_values('total_value', ascending=True)
# Sort by avg value
# qb_values.sort_values('avg_value', ascending=True)

              owner_id  avg_value  total_value        display_name
6   868657255933997056     5449.0         5449          jaywieland
1   606584542500835328     6775.0         6775  ChimpertonxHxMcgee
11  995406796682551296     7133.0         7133          jarede2205
7   871472531377451008     5342.0        10684            msmith21
2   676939846786314240     5405.0        10810           ColeB1998
10  883575245750292480     6158.0        12316      BrunsonBurner3
4   733146304376606720     6729.5        13459       BearsRDaTruth
9   880677433999859712     6779.5        13559        TKSuperMan21
5   862814489060442112     7368.0        14736            2chambzz
0   467062850880270336     7480.5        14961           makoerner
8   871485725609267200     7515.5        15031             BigDoba
3   728992249169436672     7732.0        15464             JreezyC